### ISSUE TITLE
Integration stopped working

### ISSUE THREAD

**Issue by soeter01** [pwesters/watts_vision#16]
After many months of perfect operation today the integration fails at start up with the following error in the HA log: "Something went wrong fetching user data. Code: 5, Key: ERR_ROUTE, Value: Route error, Data: {}"

Re downloading, re-configuring or  restarting HA did not help.

Any ideas?

**Comment by fabianteunissen** [comment]
I'm in the same boat.

Interestingly, the setup with a second home, complete with another Home Assistant instance and Watts integration, runs flawlessly. Cannot find any diffrences core/firmware/setting wise. I've checked for discrepancies in core, firmware, and settings, but haven't found any.

**Comment by pwesters** [comment]
I have to do some final checks but it looks like there's a trailing slash missing at line 123 of watts_api.py
So change the line from
`            url="https://smarthome.wattselectronics.com/api/v0.1/human/smarthome/read",`
to
`            url="https://smarthome.wattselectronics.com/api/v0.1/human/smarthome/read/",`
and it should not give any errors. I'll do some more investigating but if this is the solution i'll create a new release.

**Comment by fabianteunissen** [comment]
Verified your suggested modification, and it performs like a charm agian!

Unfortunately, I've already attempted to restore the second HA instance, but it's stuck in the restoration process for like an hour..

**Comment by soeter01** [comment]
Thanks pwesters for such a quick fix - it is indeed working again!

**Comment by xvb201** [comment]
I had the same issue and the suggested fix also worked for me.
