### ISSUE TITLE
Error since watts update ([custom_components.watts_vision.watts_api] Something went wrong fetching the token: 404)

### ISSUE THREAD

**Issue by stephenmaij** [pwesters/watts_vision#18]
Since yesterday around 22h CET I get this error
ERROR (SyncWorker_8) [custom_components.watts_vision.watts_api] Something went wrong fetching the token: 404

Will investigate further when I have time.

**Comment by stephenmaij** [comment]
https://smarthome.wattselectronics.com/auth/realms/watts/protocol/openid-connect/token needs to be updated to
https://auth.smarthome.wattselectronics.com/realms/watts/protocol/openid-connect/token and then its fixed

**Comment by stephenmaij** [comment]
Please accept this PR https://github.com/pwesters/watts_vision/pull/19

**Comment by pwesters** [comment]
Accepted pr #19 
Thank you @stephenmaij
